language: node_js
node_js:
  -16

services:
 - docker

before_install: # predeployment / staging
 - docker build -t jeslynnchan/youtubestatp5 -f Dockerfile.dev .

script: # deployment / staging
 -  docker run jeslynnchan/youtubestatp5 npm run test -- --coverage